### ISSUE TITLE
各方面都很好，编辑模式时选中会有点问题

### ISSUE THREAD

**Issue by eryajf** [ZekunC/Obsidian-Typora-Vue-Theme#1]
非常优秀的插件，稍微提个小意见，在编辑模式下，如果选中行内代码的内容，会看不出来选中的样式：

![image](https://user-images.githubusercontent.com/33259379/144056862-2d9c0a68-d92f-4675-b42a-9d78dd378ea2.png)

比如这个时候其实已经选中shift了，只不过看不出来。

**Comment by ZekunC** [comment]
> 非常优秀的插件，稍微提个小意见，在编辑模式下，如果选中行内代码的内容，会看不出来选中的样式：
> 
> ![image](https://user-images.githubusercontent.com/33259379/144056862-2d9c0a68-d92f-4675-b42a-9d78dd378ea2.png)
> 
> 比如这个时候其实已经选中shift了，只不过看不出来。

这个我之前注意到了，如果你切换成默认主题，仍然无法显示的，应该是底层的bug，
![image](https://user-images.githubusercontent.com/41253365/144159643-c3883254-58ad-47e9-85cf-251687a4f8bd.png)

**Comment by eryajf** [comment]
> > 非常优秀的插件，稍微提个小意见，在编辑模式下，如果选中行内代码的内容，会看不出来选中的样式：
> > ![image](https://user-images.githubusercontent.com/33259379/144056862-2d9c0a68-d92f-4675-b42a-9d78dd378ea2.png)
> > 比如这个时候其实已经选中shift了，只不过看不出来。
> 
> 这个我之前注意到了，如果你切换成默认主题，仍然无法显示的，应该是底层的bug， ![image](https://user-images.githubusercontent.com/41253365/144159643-c3883254-58ad-47e9-85cf-251687a4f8bd.png)

好的， 我尝试在其他地方反馈一下

**Comment by ZekunC** [comment]
你好，这个bug官方已经修复了。本主题已经更新为v1.0版本。
