### ISSUE TITLE
PDF Export with dark variant

### ISSUE THREAD

**Issue by ghost** [ZekunC/Obsidian-Typora-Vue-Theme#12]
Hi,

I really like this theme (I use the dark variant).
The only thing that bothers me is its look in exported PDFs.

Is it possible to optimize this?

**Comment by ZekunC** [comment]
Could you be more specific？

**Comment by ghost** [comment]
Sure, I created this page in Obsidian, but exported the code blocks are really hard to read.
![2023-04-20_20-47-09](https://user-images.githubusercontent.com/28714277/233459814-140dfdad-493c-4c2d-98ff-14f967ae2669.png)
![2023-04-20_20-47-43](https://user-images.githubusercontent.com/28714277/233459816-3501695c-7220-4fa5-b477-b6ca41c726b6.png)

**Comment by ZekunC** [comment]
This is indeed a bit of an issue, I didn't notice it before. If I have the time, I will fix it as soon as possible. As a temporary solution, you can switch to the light mode to export the PDF, and the results should be the same.

**Comment by ZekunC** [comment]
Fixed in Obsidian v1.2.8.
