### ISSUE TITLE
Regarding the bug with the left-side tag list

### ISSUE THREAD

**Issue by ok-kai** [ZekunC/Obsidian-Typora-Vue-Theme#13]
Hello author, I really like your theme! Thank you for creating such a beautiful theme.

The "selected state label" on the left side cannot be automatically refreshed!

![GIF 2023-6-16 21-41-00](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/56720916/18480aba-614c-4af3-acbf-0c45a9591b50)

It's very easy to be disturbed and select the wrong tag that I really want!

**Comment by ZekunC** [comment]
没太看懂这个图是什么意思😂可以语言描述更准确一点吗

**Comment by ok-kai** [comment]
其实我是想表达”标签状态“不会自动刷新，而是要把父标签收起再展开才会生效。

我也不太明白这个主题的”标签状态“表示

比如：

**情况一(标签选中状态)** ：

文字高亮，同时==子标签与父标签对齐==
![image](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/56720916/2c4abc1a-cbfe-4372-8097-934028da1f96)


**情况二（选中标签状态)** ：

文字高亮，==子标签未与父标签对其==
![image](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/56720916/358a74b5-b61c-41d4-ae7c-bd8dfa369c04)

**情况三（再选中A标签的时候，选中B标签）**：

B标签文字高亮，A标签与父元素对其
![image](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/56720916/928676cd-a1da-4b77-8c02-b706a46b5615)

**Comment by ok-kai** [comment]
不知道我表述清楚没😁

总之就是标签选中状态不是实时生效的**(需要将父标签展开再收起才会生效)**

![GIF 2023-6-16 22-23-30](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/56720916/7468a1d3-9694-49bb-a163-76fc0dfffdc4)

这样的话在一个有很多子标签的文件夹中，真正被选中的标签很容易被忽视

来自 Windows 10 Pro 20H2

**Comment by renfliu** [comment]
同样遇到这个问题了，在新版obsidian中，列表选中项的缩进忽大忽小

**Comment by ZekunC** [comment]
好的，应该是因为Obsidian最近更新了新版本，我最近会修复它。

**Comment by ZekunC** [comment]
I will fix it soon.

**Comment by chenbihao** [comment]
同，期待修复，这个bug太影响观感了，
不过我感觉不改变缩进更好，这是我的解决方案：

注释掉了 padding-left: 4px;  ，目前看符合我的期待，不过不知道会不会影响到其他地方 

```css
/*Navigator File BEGIN*/
.nav-file-title.is-active{
	border-radius:0;
	border-left: 4px solid hsl(var(--interactive-accent-hsl));
	/*padding-left: 4px;*/
}
/*Navigator File END*/

```

**Comment by ZekunC** [comment]
Bug is fixed in version v1.0.3.
