### ISSUE TITLE
标题选中高亮时，上方有空白

### ISSUE THREAD

**Issue by jiadong825** [ZekunC/Obsidian-Typora-Vue-Theme#14]
如图，选中标题的时候，文字下方紧贴边界但是上方却用空白。但是对于正文没有这个问题
1![image](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/78004570/e40a0a43-a8fd-4c5a-92e7-5d29b4623671)

**Comment by ZekunC** [comment]
官方的默认样式就是这种，我没改间距只改了颜色。
