### ISSUE TITLE
行内代码在列表中颜色不同

### ISSUE THREAD

**Issue by Somnia1337** [ZekunC/Obsidian-Typora-Vue-Theme#15]
如图 1、2，在实时预览模式下，行内代码的颜色统一，但在阅读模式下，有序列表和无序列表内的行内代码显示为黑色字体

我尝试了这个解决方案：在主题 css 文件中，删除 ".markdown-rendered p code" 中的 "p"，这可以修复列表中变为黑色字体的问题，但是也会导致代码块中所有本该是黑色的字变为橙色，如图 3、4

<img width="400" alt="Snipaste_231228_223945" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/84e8aa73-ee7e-4e7d-a410-dba3fd706e14">

<img width="400" alt="Snipaste_231228_223957" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/8c7026e0-e59f-4d9c-95af-7d65cf95f452">

<img width="542" alt="Snipaste_231230_155836" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/df09e0ac-3ef2-44fb-b40c-c3d514e1b558">

<img width="542" alt="Snipaste_231230_155602" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/73e9535e-bb00-4069-9a7b-8326690cc014">

**Comment by Somnia1337** [comment]
Ok I fixed this myself.

If you're having the same issue:

1. Open theme file at "\Your Vault\.obsidian\themes\Typora-Vue\theme.css
2. Locate line ".markdown-rendered p code"
3. Delete 'p'

That'll fix the problem

<img width="907" alt="Snipaste_231230_153448" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/462200cd-7c68-420b-9489-871f3b8922b9">

<img width="907" alt="Snipaste_231230_153540" src="https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/118144447/3db39456-dfe8-45f5-9ed4-31a70aabc601">

**Comment by ZekunC** [comment]
已经注意到这个问题了，我后续有时间改一下

**Comment by ZekunC** [comment]
增加一个配置即可：
```css
.markdown-rendered li code{
	color: var(--cus-inline-code-text);
}
```

效果如图：列表颜色恢复；代码块颜色仍是默认的黑色 
![image](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme/assets/41253365/b6340149-8f5a-47ed-8cb5-4655a67f1a3f)

**Comment by Somnia1337** [comment]
感谢作者大大，已经完美解决了🤩再次感谢！
