### ISSUE TITLE
在编辑模式下list前面的圆点非常大

### ISSUE THREAD

**Issue by newroc** [ZekunC/Obsidian-Typora-Vue-Theme#2]
在编辑模式下list前面的圆点非常大，预览模式的是正确的。

<img width="231" alt="image" src="https://user-images.githubusercontent.com/3711682/144645828-31fa6b4c-db94-4731-984d-326f87190fab.png">

**Comment by ZekunC** [comment]
> 在编辑模式下list前面的圆点非常大，预览模式的是正确的。
> 
> <img alt="image" width="231" src="https://user-images.githubusercontent.com/3711682/144645828-31fa6b4c-db94-4731-984d-326f87190fab.png">

我这边是正确的，没有出现你的这种情况，能否给出你的markdown代码? 
![image](https://user-images.githubusercontent.com/41253365/144693375-2e72b4a2-ae48-4646-a83d-e7073454df2e.png)

**Comment by newroc** [comment]
> 

**代码**

```
* 测试代码1
* 测试代码2 

- 测试代码三
- 测试代码四
```

**编辑模式效果**
<img width="234" alt="image" src="https://user-images.githubusercontent.com/3711682/144707188-7b626198-ed8b-44ac-96f8-69a11e232bb5.png">

**预览模式效果**
<img width="234" alt="image" src="https://user-images.githubusercontent.com/3711682/144707205-e5f72aa9-066c-4368-b597-09e5103e2193.png">

**Comment by ZekunC** [comment]
> > 
> 
> **代码**
> 
> ```
> * 测试代码1
> * 测试代码2 
> 
> - 测试代码三
> - 测试代码四
> ```
> 
> **编辑模式效果** <img alt="image" width="234" src="https://user-images.githubusercontent.com/3711682/144707188-7b626198-ed8b-44ac-96f8-69a11e232bb5.png">
> 
> **预览模式效果** <img alt="image" width="234" src="https://user-images.githubusercontent.com/3711682/144707205-e5f72aa9-066c-4368-b597-09e5103e2193.png">

我这边仍然无法复现你的错误。 我的obsidian版本是v0.12.19，是否是因为其他插件或css片段的干扰？

**Comment by newroc** [comment]
> > **代码**
> > ```
> > * 测试代码1
> > * 测试代码2 
> > 
> > - 测试代码三
> > - 测试代码四
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **编辑模式效果** <img alt="image" width="234" src="https://user-images.githubusercontent.com/3711682/144707188-7b626198-ed8b-44ac-96f8-69a11e232bb5.png">
> > **预览模式效果** <img alt="image" width="234" src="https://user-images.githubusercontent.com/3711682/144707205-e5f72aa9-066c-4368-b597-09e5103e2193.png">
> 
> 我这边仍然无法复现你的错误。 我的obsidian版本是v0.12.19，是否是因为其他插件或css片段的干扰？

我用排除法找到问题原因了，罪魁祸首是这个插件---"obsidian-outliner"。把这个插件去掉就好了 :(

**Comment by eryajf** [comment]
> 罪魁祸首是这个插件---"obsidian-outliner"

我这里也启用了这个插件，似乎也没有复现这个问题。

**Comment by newroc** [comment]
> 

那就奇怪了，我把这个插件去掉后，问题解决了，我新建了一个库，也能够再现这个问题。
