### ISSUE TITLE
升级到0.13.14在编辑模式下开启所见即所得，list 前面的点会变成2个。

### ISSUE THREAD

**Issue by newroc** [ZekunC/Obsidian-Typora-Vue-Theme#4]
<img width="556" alt="截屏2021-12-25 12 01 17" src="https://user-images.githubusercontent.com/3711682/147377149-f7dd3c0e-7be6-4fe5-ba0f-d91522baeaf9.png">

升级到0.13.14在编辑模式下开启所见即所得，list 前面的点会变成2个。

**Comment by ZekunC** [comment]
感谢反馈。做主题的时候没想到Ob还有所见即所得的功能..... 这样的话应该不止这一个地方有问题....  🥱

**Comment by newroc** [comment]
其他的貌似其他功能都挺正常的

**Comment by ZekunC** [comment]
你好，已经在最新版v1.0修复了。
