### ISSUE TITLE
如何修改列表的显示样式？

### ISSUE THREAD

**Issue by flyflypeng** [ZekunC/Obsidian-Typora-Vue-Theme#5]
想请教一下如何修改css样式表文件，将预览模式中list列表前面的花括号去除掉呀，个人看着不是很习惯，觉得优点突兀，谢谢！

例如：图片中这种list样式
![image](https://user-images.githubusercontent.com/8475378/159526575-abce8596-2325-4a5b-8c2f-05351e7ef9bd.png)
``

**Comment by ZekunC** [comment]
你好，已经在最新版v1.0删除这些线条了。
