### ISSUE TITLE
在实时编辑模式下，css没生效

### ISSUE THREAD

**Issue by ashtime99** [ZekunC/Obsidian-Typora-Vue-Theme#6]
实时编辑模式：
![image](https://user-images.githubusercontent.com/75244264/179492741-0b01f3f2-ae5a-414c-97a9-31ac28ac31c2.png)
预览模式没有问题
![image](https://user-images.githubusercontent.com/75244264/179492887-a1bf18d0-0d4c-48c7-a5c3-d8f65591ab2a.png)

**Comment by ZekunC** [comment]
你好，已经在最新版v1.0修复了。
