### ISSUE TITLE
希望作者可以统一一下配色样式

### ISSUE THREAD

**Issue by Augu1sto** [ZekunC/Obsidian-Typora-Vue-Theme#7]
typora-vue的主题色是绿色，但是代码块复制按钮的颜色是蓝色，表格预览高亮也是蓝色，总觉得不太和谐

**Comment by ZekunC** [comment]
你好，已经在最新版**v1.0**修复了。

**Comment by weikefan123** [comment]
您好 怎么更改行间距 自己弄了半天都没生效 麻烦您了
